#!/usr/bin/env bash

usage() {
  echo "Usage: $0 [-s] [-c] <minecraft 1.21.1 folder>"
  echo "  Example: $0 ~/.local/share/PolyMC/instances/1.21.1/.minecraft"
		echo "-s:								set this flag to true if you're running on srever"
		echo "-c:								high, mid, low: PC capabiliities to install
		optional mods and resource packs"

  exit 1  # Exit with an error code (non-zero)
}

# Check if an argument is provided
cleanup() {
				if [ $# -eq 0 ]; then
								echo "Error: No folder provided."
								usage  # Call usage() and exit
								exit
				fi
}


while getopts 'sc:d:' flag; do
  case "${flag}" in
    s) SERVER="true" ;;
    c) CLIENT_PRI="${OPTARG}" ;;
    d) MC_DIR="${OPTARG}" ;;
    *) usage ;;
  esac
done
if [ -z "$MC_DIR" ] || ([ -z "$SERVER" ] && [ -z "$CLIENT_PRI" ]); then
				usage
elif [ -n "$SERVER" ] && [ -n "$CLIENT_PRI" ]; then
				echo "$SERVER $CLIENT_PRI"
				echo "Can't be both buddy. Pick a side. Server or Client?" usage fi
fi

echo "$SERVER"
echo "$CLIENT_PRI"
echo "$MC_DIR"



MODS_FOLDER="$MC_DIR/mods"
RESOURCEPACKS_FOLDER="$MC_DIR/resourcepacks"
DATAPACKS_FOLDER="$MC_DIR/world/datapacks"


download_array() {
				local -n arr=$1
				echo "$arr"

				for name in "${!arr[@]}"; do
								url="${arr[$name]}"
								filename=$(python3 -c "import urllib.parse; print(urllib.parse.unquote('${url##*/}'))")
								filepath="$2/$filename"
								echo "$name   $filepath"
								if [[ -f "$filepath" ]]; then
												echo "Already exists: $filepath"
								else
												echo "Downloading..."
												echo ""
												wget -q --show-progress -O "$filepath" "$url"
								fi
				done
}

# TODO: Optionally Remove Mods, Resources and Data Packs
# 						that are not in the arrays.


declare -A client_and_server_mods=(
				["Fabric API"]="https://cdn.modrinth.com/data/P7dR8mSH/versions/IpaMcBLh/fabric-api-0.116.11%2B1.21.1.jar" # Fabric API
				["Aether"]="https://cdn.modrinth.com/data/YhmgMVyu/versions/NSqdh1i9/aether-1.21.1-1.5.11-fabric.jar" # Aether: Adds a new dimension
				["OwO-Lib"]="https://cdn.modrinth.com/data/ccKDOlHs/versions/JB1fLQnc/owo-lib-0.12.15.4%2B1.21.jar" ## Dependencies: owo-lib
				["Vanilla Backport"]="https://cdn.modrinth.com/data/6xwxDTgf/versions/wAeQBuFY/VanillaBackport-fabric-1.21.1-1.1.6.3.jar"
				["Platform"]="https://cdn.modrinth.com/data/i6fiqm5y/versions/WeSu6O41/Platform-fabric-1.21.1-1.3.jar"
				["Lootr"]="https://cdn.modrinth.com/data/EltpO5cN/versions/Rxyok2IC/lootr-fabric-1.21.1-1.11.37.118.jar"
				["Easy Magic"]="https://cdn.modrinth.com/data/9hx3AbJM/versions/LLLfoeWJ/EasyMagic-v21.1.4-1.21.1-Fabric.jar"
				["PuzzlesLib"]="https://cdn.modrinth.com/data/QAGBst4M/versions/L007zH3l/PuzzlesLib-v21.1.39-1.21.1-Fabric.jar"
				["Trade Cycling"]="https://cdn.modrinth.com/data/qpPoAL6m/versions/g1AEWhmh/trade-cycling-fabric-1.21.1-1.0.20.jar"
				["Creeper Overhaul"]="https://cdn.modrinth.com/data/MI1LWe93/versions/O6yuPiE8/CreeperOverhaul-fabric-1.21.1-4.0.6.jar"
				["geckolib"]="https://cdn.modrinth.com/data/8BmcQJ2H/versions/3GjkJptS/geckolib-fabric-1.21.1-4.8.4.jar"
				["Resourcefullib"]="https://cdn.modrinth.com/data/G1hIVOrD/versions/Hf91FuVF/resourcefullib-fabric-1.21-3.0.12.jar"
				["Resourcefulconfig"]="https://cdn.modrinth.com/data/M1953qlQ/versions/dQh99ERC/resourcefulconfig-fabric-1.21-3.0.11.jar"
				["Nyf's Spiders"]="https://cdn.modrinth.com/data/dOGM7ccu/versions/D1hskQ7T/nyfsspiders-fabric-1.21.1-3.0.1.jar"
				["Better Nether Map"]="https://cdn.modrinth.com/data/fdtm99de/versions/BEfm3cNd/nethermap-4.0.0-1.21.1.jar"
)

declare -A server_only_mods=(
				# Repeated from client_optional
				["FerriteCore"]="https://cdn.modrinth.com/data/uXXizFIs/versions/sOzRw3CG/ferritecore-7.0.3-fabric.jar" # FerriteCore: Server and Client Side Optimizations
				["Lithium"]="https://cdn.modrinth.com/data/gvQqBUqZ/versions/XQJtuOTA/lithium-fabric-0.15.3%2Bmc1.21.1.jar"
				
				# Strictly Server Only
				["Map Distance Fix"]="https://cdn.modrinth.com/data/51BNNAng/versions/JgekedTR/mapdistancefix-fabric-1.1.1%2Bmc1.21-1.21.11.jar"
				["ServerCore"]="https://cdn.modrinth.com/data/4WWQxlQP/versions/FDzBkBBD/servercore-fabric-1.5.10%2B1.21.1.jar"
				["Let Me Despawn"]="https://cdn.modrinth.com/data/vE2FN5qn/versions/Wb7jqi55/letmedespawn-1.21.x-fabric-1.5.0.jar"
				["Almanac"]="https://cdn.modrinth.com/data/Gi02250Z/versions/hUgNmeCO/Almanac-1.21.1-2-fabric-1.5.2.jar"
				["Concurrent Chunk Management Engine"]="https://cdn.modrinth.com/data/VSNURh3q/versions/DSqOVCaF/c2me-fabric-mc1.21.1-0.3.0%2Balpha.0.362.jar"
				["Clumps"]="https://cdn.modrinth.com/data/Wnxd13zP/versions/3ene3W1l/Clumps-fabric-1.21.1-19.0.0.1.jar"
				["ModernFix"]="https://cdn.modrinth.com/data/nmDcB62a/versions/NnNX8LBn/modernfix-fabric-5.25.1%2Bmc1.21.1.jar"
				["ScalableLux"]="https://cdn.modrinth.com/data/Ps1zyz6x/versions/Yx1tgJMI/ScalableLux-0.1.0.1%2Bfabric.d0d58ab-all.jar"
				["Get It Together, Drops!"]="https://cdn.modrinth.com/data/T0OUgf8P/versions/SONCHAXQ/getittogetherdrops-fabric-1.21-1.3.1.jar"
				["spark"]="https://cdn.modrinth.com/data/l6YH9Als/versions/cALUj9l1/spark-1.10.109-fabric.jar"
				["Chunky"]="https://cdn.modrinth.com/data/fALzjamp/versions/RVFHfo1D/Chunky-Fabric-1.4.23.jar"
				["Krypton"]="https://cdn.modrinth.com/data/fQEb0iXm/versions/Acz3ttTp/krypton-0.2.8.jar"
				["RightClickHarvest"]="https://cdn.modrinth.com/data/Cnejf5xM/versions/54VwuB27/rightclickharvest-fabric-4.6.1%2B1.21.1.jar"
				["JamLib"]="https://cdn.modrinth.com/data/IYY9Siz8/versions/wWGzYPkM/jamlib-fabric-1.3.6%2B1.21.1.jar"
				["Architectury"]="https://cdn.modrinth.com/data/lhGA9TYQ/versions/Wto0RchG/architectury-13.0.8-fabric.jar"
)

declare -A client_pri_A=(
				["Krypton"]="https://cdn.modrinth.com/data/fQEb0iXm/versions/Acz3ttTp/krypton-0.2.8.jar"
)

declare -A client_pri_B=(
				["Distant Horizons"]="https://cdn.modrinth.com/data/uCdwusMi/versions/KkaaQtTD/DistantHorizons-3.0.2-b-1.21.1-fabric-neoforge.jar"

				["FerriteCore"]="https://cdn.modrinth.com/data/uXXizFIs/versions/sOzRw3CG/ferritecore-7.0.3-fabric.jar" # FerriteCore: Server and Client Side Optimizations


				["Sodium"]="https://cdn.modrinth.com/data/AANobbMI/versions/u1OEbNKx/sodium-fabric-0.6.13%2Bmc1.21.1.jar"
				["Iris"]="https://cdn.modrinth.com/data/YL57xq9U/versions/zsoi0dso/iris-fabric-1.8.8%2Bmc1.21.1.jar"
				["Lithium"]="https://cdn.modrinth.com/data/gvQqBUqZ/versions/XQJtuOTA/lithium-fabric-0.15.3%2Bmc1.21.1.jar"
				["ImmediatelyFast"]="https://cdn.modrinth.com/data/5ZwdcRci/versions/yHztKxR5/ImmediatelyFast-Fabric-1.6.10%2B1.21.1.jar"
				["Mod Menu"]="https://cdn.modrinth.com/data/mOgUt4GM/versions/v6Xx3fbU/modmenu-11.0.4.jar"
				["Resourcify"]="https://cdn.modrinth.com/data/RLzHAoZe/versions/HrAVb2x8/Resourcify%20%281.21.1-fabric%29-1.8.1.jar"
				["fabric-language-kotlin"]="https://cdn.modrinth.com/data/Ha28R6CL/versions/2i87JpYj/fabric-language-kotlin-1.13.11%2Bkotlin.2.3.21.jar"
				["Bridging"]="https://cdn.modrinth.com/data/Gi02250Z/versions/hUgNmeCO/Almanac-1.21.1-2-fabric-1.5.2.jar"
				["Stack to Nearby Chests"]="https://cdn.modrinth.com/data/HtGckJVc/versions/Ycxx5lTa/stack-to-nearby-chests-mc1.21.1-0.5.10.jar"
				["EMI"]="https://cdn.modrinth.com/data/fRiHVvU7/versions/mYQ3bJs5/emi-1.1.22%2B1.21.1%2Bfabric.jar"

)


declare -A resource_packs=(
				["Blue Netherite"]="https://cdn.modrinth.com/data/OL1EGja1/versions/7hJVbB8Q/Blue%20netherite%5B1.1.3%5D.zip"
)

# Mods required by Resource Packs
declare -A client_resource_mods=(

)

if [ -z "$SERVER" ]; then
				case "${CLIENT_PRI}" in
								high)
												download_array client_pri_B "$MODS_FOLDER"
												download_array client_resource_mods "$MODS_FOLDER"
												download_array resource_packs "$RESOURCEPACKS_FOLDER"
												;&
								mid) download_array client_pri_A "$MODS_FOLDER" ;&
								*) echo "Done :)" ;;
				esac
else
				download_array server_only_mods "$MODS_FOLDER"
fi

download_array client_and_server_mods "$MODS_FOLDER" 

