#!/usr/bin/env bash

usage() {
  echo "Usage: $0 <minecraft 1.21.1 folder>"
  echo "  Example: $0 ~/.local/share/PolyMC/instances/1.21.1/.minecraft"
  exit 1  # Exit with an error code (non-zero)
}

# Check if an argument is provided
if [ $# -eq 0 ]; then
  echo "Error: No folder provided."
  usage  # Call usage() and exit
fi
 
# Greet the user
mc_folder="$1"

mkdir -p "$mc_folder/mods/"
cd "$mc_folder/mods/"





# Fabric API
wget https://cdn.modrinth.com/data/P7dR8mSH/versions/IpaMcBLh/fabric-api-0.116.11%2B1.21.1.jar


# FerriteCore: Server and Client Side Optimizations
wget https://cdn.modrinth.com/data/uXXizFIs/versions/sOzRw3CG/ferritecore-7.0.3-fabric.jar


# Aether: Adds a new dimension
wget https://cdn.modrinth.com/data/YhmgMVyu/versions/NSqdh1i9/aether-1.21.1-1.5.11-fabric.jar
## Dependencies: owo-lib
wget https://cdn.modrinth.com/data/ccKDOlHs/versions/JB1fLQnc/owo-lib-0.12.15.4%2B1.21.jar
